stages:
  - build
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# buld docker image
docker_build:
  stage: build
  image: docker:stable
  script:
    - docker build -t $DOCKER_IMAGE_NAME --build-arg ACCESS_KEY_ID="${ACCESS_KEY_ID}" --build-arg SECRET_ACCESS_KEY="${SECRET_ACCESS_KEY}" .
    - echo $REGISTRY_PASS | docker login $REGISTRY_HOST/v2/ -u $REGISTRY_USER --password-stdin
    - docker tag $DOCKER_IMAGE_NAME $REGISTRY_HOST/v2/$DOCKER_IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY_HOST/v2/$DOCKER_IMAGE_NAME:$CI_COMMIT_REF_NAME
  tags:
    - docker